### ISSUE TITLE
Is it possible to make the emitter pluggable, or at least consider using mitt?

### ISSUE THREAD

**Issue by saas786** [MasatoMakino/raf-ticker#182]
The current implementation with `eventemitter3` could be seamlessly replaced with `mitt`.

Alternatively, could you provide a way to easily replace the emitter in my code, making it more modular and customizable?

Just a thought—perhaps you’ve already considered something along these lines when incorporating the emitter.

**Comment by MasatoMakino** [comment]
Thank you for your suggestion!

Currently, there are no plans to make the event emitter pluggable or to switch to mitt. We chose eventemitter3 because of its strong TypeScript type system, which aligns well with RAFTicker's goal of wrapping window.requestAnimationFrame.

RAFTicker operates as a singleton, centralizing requestAnimationFrame callbacks. Making this global singleton more modular could lead to unnecessary complexity and confusion for users.

I appreciate your feedback and will keep it in mind as the project evolves.

Thanks again for your input!
